### PR TITLE
Delete FalseSubcommand.java

### PR DESCRIPTION
**Pull request by steviebeenz**
@MSWS This should fix the issue... May also need to delete more, IDK.

### CODE REVIEW

**Comment by MSWS** [comment]
Or just delete the webhook from discord ¯\_(ツ)_/¯

**Comment by steviebeenz** [comment]
@MSWS the command still exists though... IDK.

**Comment by steviebeenz** [comment]
@MSWS Maybe just not register the command...

**Comment by steviebeenz** [comment]
Oops

**Comment by steviebeenz** [comment]
@MSWS should work I just commented out the reference.

**Comment by steviebeenz** [comment]
@MSWS Your verdict on the PR?

**Pull request closed without merging**
